"""initial schema

The consolidated Phase 6 baseline: every table the app defines (the Phase 2 delivery/
state tables, the Phase 3 advertiser hierarchy, and the Phase 4 social graph + real ad
events) in one revision. Autogenerated from app.models against an empty database, so it is
an exact mirror of Base.metadata — the same schema init_db() builds via create_all in dev.
In production the container entrypoint runs `alembic upgrade head` before uvicorn, so Alembic
owns the schema; create_all then no-ops.

Revision ID: a190004afaa9
Revises:
Create Date: 2026-07-13 20:59:37.435672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a190004afaa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_click',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('impression_id', sa.String(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('viewer_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_click', schema=None) as batch_op:
        batch_op.create_index('ix_click_impression', ['impression_id'], unique=False)

    op.create_table('ad_conversion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('click_id', sa.String(), nullable=False),
    sa.Column('impression_id', sa.String(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('viewer_user_id', sa.String(), nullable=False),
    sa.Column('value_micros', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_conversion', schema=None) as batch_op:
        batch_op.create_index('ix_conv_impression', ['impression_id'], unique=False)

    op.create_table('ad_impression',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('ad_set_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('viewer_user_id', sa.String(), nullable=False),
    sa.Column('segment_key', sa.String(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('age_band', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('clearing_micros', sa.Integer(), nullable=False),
    sa.Column('spend_micros', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.Integer(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_impression', schema=None) as batch_op:
        batch_op.create_index('ix_imp_campaign_time', ['campaign_id', 'created_at'], unique=False)
        batch_op.create_index('ix_imp_viewer_time', ['viewer_user_id', 'created_at'], unique=False)

    op.create_table('ad_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('bid_micros', sa.Integer(), nullable=False),
    sa.Column('bid_strategy', sa.String(), nullable=False),
    sa.Column('targeting_json', sa.Text(), nullable=False),
    sa.Column('freq_cap_impressions', sa.Integer(), nullable=True),
    sa.Column('freq_cap_per_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_sets', schema=None) as batch_op:
        batch_op.create_index('ix_adset_campaign', ['campaign_id'], unique=False)

    op.create_table('ads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ad_set_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('creative_json', sa.Text(), nullable=False),
    sa.Column('adomain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.create_index('ix_ad_adset', ['ad_set_id'], unique=False)

    op.create_table('advertiser_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('segment_key', sa.String(), nullable=False),
    sa.Column('line_ad_id', sa.String(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('winner_seat', sa.String(), nullable=False),
    sa.Column('winner_ad_id', sa.String(), nullable=False),
    sa.Column('clearing_micros', sa.Integer(), nullable=False),
    sa.Column('floor_micros', sa.Integer(), nullable=False),
    sa.Column('min_to_win_micros', sa.Integer(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=False),
    sa.Column('filtered_count', sa.Integer(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('bids_json', sa.Text(), nullable=False),
    sa.Column('notices_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_state',
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('ad_set_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('sim_day', sa.Integer(), nullable=False),
    sa.Column('spent_today_micros', sa.Integer(), nullable=False),
    sa.Column('spent_lifetime_micros', sa.Integer(), nullable=False),
    sa.Column('daily_budget_micros', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ad_id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('daily_budget_micros', sa.Integer(), nullable=False),
    sa.Column('pacing', sa.String(), nullable=False),
    sa.Column('baseline_conv_value_micros', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaign_account', ['account_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('ix_comment_post_time', ['post_id', 'created_at'], unique=False)

    op.create_table('delivery_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('ad_set_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('auctions', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('spend_micros', sa.Integer(), nullable=False),
    sa.Column('revenue_micros', sa.Integer(), nullable=False),
    sa.Column('covered_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.Column('breakdowns', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'bucket_start', 'source', name='uq_delivery_bucket')
    )
    with op.batch_alter_table('delivery_bucket', schema=None) as batch_op:
        batch_op.create_index('ix_delivery_campaign_time', ['campaign_id', 'bucket_start'], unique=False)
        batch_op.create_index('ix_delivery_time', ['bucket_start'], unique=False)

    op.create_table('follows',
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('followee_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('ix_follow_followee', ['followee_id'], unique=False)

    op.create_table('freq_cap_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('sim_day', sa.Integer(), nullable=False),
    sa.Column('segment_key', sa.String(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'sim_day', 'segment_key', name='uq_freq_cap')
    )
    op.create_table('learning_state',
    sa.Column('ad_set_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('accumulated_signal', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('in_learning', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ad_set_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index('ix_like_post', ['post_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('read_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_msg_recipient', ['recipient_id', 'created_at'], unique=False)
        batch_op.create_index('ix_msg_sender', ['sender_id', 'created_at'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('ix_post_author_time', ['author_id', 'created_at'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_seed', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('interests_json', sa.Text(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('age_band', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reach_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('segment_key', sa.String(), nullable=False),
    sa.Column('cum_impressions', sa.Integer(), nullable=False),
    sa.Column('reached_est', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'segment_key', name='uq_reach_state')
    )
    op.create_table('sim_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('tick_hz', sa.Float(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('market_density', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_handle'), ['handle'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_handle'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sim_control')
    op.drop_table('reach_state')
    op.drop_table('profiles')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_post_author_time')

    op.drop_table('posts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_msg_sender')
        batch_op.drop_index('ix_msg_recipient')

    op.drop_table('messages')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('ix_like_post')

    op.drop_table('likes')
    op.drop_table('learning_state')
    op.drop_table('freq_cap_counter')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('ix_follow_followee')

    op.drop_table('follows')
    with op.batch_alter_table('delivery_bucket', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_time')
        batch_op.drop_index('ix_delivery_campaign_time')

    op.drop_table('delivery_bucket')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_post_time')

    op.drop_table('comments')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaign_account')

    op.drop_table('campaigns')
    op.drop_table('budget_state')
    op.drop_table('auction_sample')
    op.drop_table('advertiser_accounts')
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index('ix_ad_adset')

    op.drop_table('ads')
    with op.batch_alter_table('ad_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_adset_campaign')

    op.drop_table('ad_sets')
    with op.batch_alter_table('ad_impression', schema=None) as batch_op:
        batch_op.drop_index('ix_imp_viewer_time')
        batch_op.drop_index('ix_imp_campaign_time')

    op.drop_table('ad_impression')
    with op.batch_alter_table('ad_conversion', schema=None) as batch_op:
        batch_op.drop_index('ix_conv_impression')

    op.drop_table('ad_conversion')
    with op.batch_alter_table('ad_click', schema=None) as batch_op:
        batch_op.drop_index('ix_click_impression')

    op.drop_table('ad_click')
    # ### end Alembic commands ###
